# Generated by Django 5.1.4 on 2024-12-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemaster',
            old_name='student',
            new_name='student_rel',
        ),
    ]
