# Generated by Django 5.1.4 on 2024-12-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_rename_student_profilemaster_student_rel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmaster',
            name='code',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
