# Generated by Django 5.1.4 on 2024-12-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_remove_studentmaster_code_profilemaster_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemaster',
            name='code',
        ),
        migrations.AddField(
            model_name='studentmaster',
            name='code',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
