# Generated by Django 5.1.4 on 2024-12-18 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_remove_profilemaster_code_studentmaster_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemaster',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8c081e6b-22b6-4ebc-a772-e9e5ab8cc263'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentmaster',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3d641c38-5751-42d3-93ba-47dd700f4e71'), editable=False, primary_key=True, serialize=False),
        ),
    ]
