# Generated by Django 5.1.4 on 2024-12-18 10:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0008_alter_profilemaster_id_alter_studentmaster_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemaster',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d0b8e6ab-6c63-46b5-a6be-091a76117f2a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentmaster',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c20c542f-e3fc-4df3-9595-331f497f27cb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
