# Generated by Django 5.1.4 on 2024-12-18 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0009_alter_profilemaster_id_alter_studentmaster_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemaster',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5f58b632-ec79-4c20-88be-83217898a945'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profilemaster',
            name='student_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.studentmaster'),
        ),
        migrations.AlterField(
            model_name='studentmaster',
            name='id',
            field=models.UUIDField(default=uuid.UUID('072a1056-6edc-4f59-8d72-4de32a63560f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
